name: Nonci
recipe: laravel
proxxy:
  web:
    - Nonci.lndo.site
  web2:
    - admin.Nonci.lndo.site
services:
  appserver:
    xdebug: false
  database:
    portforward: 3305
config:
  via: nginx
  php: '8.1'
  webroot: public
  composer_version: '2.2.12'
  database: mysql
